# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
#  release:
#    types: [created]
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
    - run: mvn -B package --file pom.xml
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging

    - name: Publish to GitHub Packages Apache Maven
    - run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

#    - name: Upload JAR
#      uses: actions/upload-artifact@v2
#      with:
#        name: artifact
#        path: target/com.zjw.login-0.0.2-SNAPSHOT.jar


#    - name: Beanstalk Deploy
#      uses: einaregilsson/beanstalk-deploy@v18
#      with:
#        aws_access_key: AKIASFFZLRX36SLETED6
#        aws_secret_key: v+AFJXv/Bm6CBmBnBfKCzDTqw4NuurO2VHy0uMp2
#        application_name: springbootwebapi
#        environment_name: Springbootwebapi-env
#        version_label: Sample Application
#        region: us-east-2
#        deployment_package: com.zjw.login-0.0.2-SNAPSHOT.jar
